services:
  api:
    container_name: api
    image: go-api:air
    pull_policy: never
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: air
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - ..:/app
      - /app/tmp
      - go_build_cache:/root/.cache/go-build
      - go_pkg_cache:/go/pkg/mod

volumes:
  go_build_cache:
  go_pkg_cache:
